version: '3'
services:
  golang-app:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - react-go-app
    env_file:
      - ./server/.env
    depends_on:
      - 'mongo'
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure


  react-app:
    build: ./client/
    ports:
      - "3000:3000"
    networks:
      - react-go-app
    volumes:
      - "./client/src:/app/src"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  
  mongo:
    container_name: mongo
    image: mongo:latest
    networks:
      - react-go-app
    volumes:
      - "mongo-data:/data/db"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure


networks:
  react-go-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
